/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer-optimized.glb -T 
Files: computer-optimized.glb [486.38KB] > A:\Portfolio\my-project\public\models\computer-optimized-transformed.glb [39.72KB] (92%)
*/

import React, { useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { loadCachedModel } from '../../utils/modelCache.js'

function ComputerContent({ url, ...props }) {
  const { nodes, materials } = useGLTF(url)
  return (
    <group {...props} dispose={null}>
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_1.geometry} material={materials['ComputerDesk.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_2.geometry} material={materials['FloppyDisk.001']} />
      </group>
    </group>
  )
}

export function Computer(props) {
  const [modelUrl, setModelUrl] = useState(null);

  useEffect(() => {
    loadCachedModel('/models/computer-optimized-transformed.glb').then(setModelUrl);
  }, []);

  if (!modelUrl) return null;
  return <ComputerContent url={modelUrl} {...props} />
}
